services:
  consul:
    image: hashicorp/consul:1.16.2
    container_name: consul-server
    ports:
      - "8500:8500"
    command: "agent -server -bootstrap -ui -client=0.0.0.0"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      retries: 3
      timeout: 5s

  api-gateway:
    build:
      context: ./apiGateway
    container_name: api-gateway
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONSUL_HOST=consul-server:8500
    depends_on:
      consul:
        condition: service_healthy
      user-service:
        condition: service_started
    networks:
      - app-network

  user-service:
    build:
      context: ./
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONSUL_HOST=consul-server
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - app-network

  workout-service:
    build:
      context: ./programGenerator
    container_name: workout-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONSUL_HOST=consul-server
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - app-network

  refactor-service:
    build:
      context: ./dataRefactor
    container_name: refactor-service
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONSUL_HOST=consul-server
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 3
      timeout: 5s

networks:
  app-network:
    driver: bridge