spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: input-route
          uri: http://localhost:8080
          predicates:
            - Path=/input/**
          filters:
            - CircuitBreaker=name=inputCircuitBreaker, fallbackUri=/fallback

        - id: health-check
          uri: http://localhost:8080/actuator/health
          predicates:
            - Path=/input/health

        - id: refactor-route
          uri: http://localhost:8090/refactor/**
          predicates:
            - Path=/refactor/**
          filters:
            - CircuitBreaker=name=refactorCircuitBreaker, fallbackUri=/fallback

        - id: refactor-health-check
          uri: http://localhost:8090/actuator/health
          predicates:
            - Path=/refactor/health

      discovery:
        locator:
          enabled: true

    consul:
      discovery:
        service-name: api-gateway
        port: 8081

    management:
      endpoints:
        web:
          exposure:
            include: health, info
      health:
        consul:
          enabled: true
        diskspace:
          enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000ms

    instances:
      refactorCircuitBreaker:
        base-config: default
        sliding-window-size: 5
      inputCircuitBreaker:
        base-config: default
        sliding-window-size: 5

server:
  port: 8081